{% set version = "1.1" %}

package:
  name: jxrlib
  version: {{ version }}

source:
  url: http://http.debian.net/debian/pool/main/j/jxrlib/jxrlib_{{ version }}.orig.tar.gz
  sha256: c7287b86780befa0914f2eeb8be2ac83e672ebd4bd16dc5574a36a59d9708303
  patches:
    - usecmake.patch  # [unix]
    - define_byteswap.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('jxrlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/lib/libjxrglue${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/libjpegxr${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\libjxrglue.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\libjpegxr.lib exit 1  # [win]

about:
  home: https://packages.debian.org/source/sid/jxrlib
  license: BSD-2-Clause
  summary: "jxrlib - JPEG XR Library by Microsoft, built from Debian hosted sources."
  description: "This package seems to be no longer maintained by the original developer (Microsoft)."
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - csachs
    - hmaarrfk
